/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var database_pb = require('./database_pb.js');
goog.exportSymbol('proto.bzn_msg', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bzn_msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bzn_msg.oneofGroups_);
};
goog.inherits(proto.bzn_msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bzn_msg.displayName = 'proto.bzn_msg';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bzn_msg.oneofGroups_ = [[10,11]];

/**
 * @enum {number}
 */
proto.bzn_msg.MsgCase = {
  MSG_NOT_SET: 0,
  DB: 10,
  JSON: 11
};

/**
 * @return {proto.bzn_msg.MsgCase}
 */
proto.bzn_msg.prototype.getMsgCase = function() {
  return /** @type {proto.bzn_msg.MsgCase} */(jspb.Message.computeOneofCase(this, proto.bzn_msg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bzn_msg.prototype.toObject = function(opt_includeInstance) {
  return proto.bzn_msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bzn_msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bzn_msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    db: (f = msg.getDb()) && database_pb.database_msg.toObject(includeInstance, f),
    json: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bzn_msg}
 */
proto.bzn_msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bzn_msg;
  return proto.bzn_msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bzn_msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bzn_msg}
 */
proto.bzn_msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10:
      var value = new database_pb.database_msg;
      reader.readMessage(value,database_pb.database_msg.deserializeBinaryFromReader);
      msg.setDb(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setJson(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bzn_msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bzn_msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bzn_msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bzn_msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDb();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      database_pb.database_msg.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional database_msg db = 10;
 * @return {?proto.database_msg}
 */
proto.bzn_msg.prototype.getDb = function() {
  return /** @type{?proto.database_msg} */ (
    jspb.Message.getWrapperField(this, database_pb.database_msg, 10));
};


/** @param {?proto.database_msg|undefined} value */
proto.bzn_msg.prototype.setDb = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.bzn_msg.oneofGroups_[0], value);
};


proto.bzn_msg.prototype.clearDb = function() {
  this.setDb(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.bzn_msg.prototype.hasDb = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string json = 11;
 * @return {string}
 */
proto.bzn_msg.prototype.getJson = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.bzn_msg.prototype.setJson = function(value) {
  jspb.Message.setOneofField(this, 11, proto.bzn_msg.oneofGroups_[0], value);
};


proto.bzn_msg.prototype.clearJson = function() {
  jspb.Message.setOneofField(this, 11, proto.bzn_msg.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.bzn_msg.prototype.hasJson = function() {
  return jspb.Message.getField(this, 11) != null;
};


goog.object.extend(exports, proto);
