const {includes, filter} = require('lodash');
const {readFileSync, readdirSync} = require('fs');

const PATH_TO_DAEMON = '../../daemon-build';

module.exports = {
    logFileExists: () => {
        // Log file is generated by Daemon in /output folder
        return filter(logDirContent('/output'), file => includes(file, '.log'))[0];
    },
    logFileMoved: logFileName => {
        // Log file is moved to /output/logs after Daemon is stopped
        return filter(logDirContent('/output/logs'), files => includes(files, logFileName))[0];
    },
    readFile: (dirPath, logFileName) => {
        return readFileSync(PATH_TO_DAEMON + dirPath + logFileName, 'utf8');
    }
};

const logDirContent = path =>
    readdirSync(PATH_TO_DAEMON + path);
